---
title: "drives_infor"
author: "Lanlan_Qing"
date: "2025-11-14"
output: html_document


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
```

## Driver Information Involving Fatal Accidents

### Import Data
```{r}

fatal_driver_infor = read_csv("./data_fatal/fatal_accidents_drivers.csv") |>
  janitor::clean_names()


total_driver_infor = read_csv("./data_origin/drivers.csv") |>
  janitor::clean_names() |>
  mutate(driver = paste0(forename, " ", surname)) |>
  select(driver, dob, nationality, url)

# Join by fatal data
fatal_driver_df = left_join(fatal_driver_infor, total_driver_infor)
```

### Supplementary information 

```{r}

missing_driver_row = fatal_driver_df |>
  filter(is.na(dob)) |>
  mutate(dob = ymd(c("1923-05-08","1928-10-23", "1932-11-15", "1927-04-16", "1936-06-23", "1932-12-22",
                      "1941-06-24", "1943-07-21", "1979-01-13")),
          nationality = c("British", "Italian", "American", "American", "British", "British", "Australian",
                          "Austrian", "Spanish"),
          url = c("https://en.wikipedia.org/wiki/Cameron_Earl",
                  "https://en.wikipedia.org/wiki/Mario_Alborghetti",
                  "https://en.wikipedia.org/wiki/Jerry_Unser_Jr.",
                  "https://en.wikipedia.org/wiki/Bob_Cortner",
                  "https://en.wikipedia.org/wiki/Shane_Summers",
                  "https://en.wikipedia.org/wiki/Martin_Brain",
                  "http://www.motorsportmemorial.org/focus.php?db=ct&n=1958",
                  "https://en.wikipedia.org/wiki/Fritz_Glatz",
                  "https://en.wikipedia.org/wiki/Mar%C3%ADa_de_Villota"
          ),
         age = ifelse(driver == "Martin Brain", 37, age)
         ) 


fatal_driver_df_remaining = fatal_driver_df |>
  anti_join(missing_driver_row, by = "driver")

combined_fatal_driver_df = bind_rows(fatal_driver_df_remaining, missing_driver_row) |>
  mutate(date_of_accident = mdy(date_of_accident)) |>
# Fix date transfer problem
  mutate(original_year = year(date_of_accident),
         corrected_year = ifelse(original_year > 2025, original_year - 100, original_year),
         date_of_accident = make_date(year = corrected_year, month = month(date_of_accident), 
                                      day = day(date_of_accident))) |>
           select(-original_year, corrected_year)
  
```

### Clean Data for Fatal Accidents' Reasons

```{r}
reason_fatal_df =  read_csv("./data_fatal/red_flags.csv") |>
  janitor::clean_names() |>
  mutate(resumed = case_match(
    resumed,
    "Y" ~ "Resumed",
    "N" ~ "Not Resumed",
    "R" ~ "Restart",
    "S" ~ "Suspended"
  )) |>
  mutate(incident = str_remove(incident, "\\."))



# Separate "rain" and "crash" factors from same cell
crash_rain_slice_view = reason_fatal_df |>
  filter(str_detect(incident,"[Rr]ain") & str_detect(incident, "[Cc]rash"))
  
crash_rain_slice_df = crash_rain_slice_view |>
  separate_rows(incident, sep = " and ") 

crash_rain_slice_df[2, "incident"] = "crashes involving Wilson Fittipaldi, Jochen Mass, John Watson, Carlos Pace, Jody Scheckter, James Hunt, Mark Donohue." 
crash_rain_slice_df[8, "incident"] = "crashes involving Jenson Button, Nico Rosberg, Adrian Sutil, Lewis Hamilton, Scott Speed, Vitantonio Liuzzi." 
crash_rain_slice_df[11, "incident"] = "crashes of Sébastien Buemi, Sebastian Vettel, Giancarlo Fisichella." 

crash_rain_slice_df = crash_rain_slice_df |> slice(-c(3, 6, 9, 12))

# Substitute new incident df edition to original
crash_rain_remaining_df = anti_join(reason_fatal_df, crash_rain_slice_view, by = "incident") 

reason_fatal_df1 = bind_rows(crash_rain_remaining_df, crash_rain_slice_df )




# Separate factors
crash_df = reason_fatal_df1 |>
 filter(str_detect(incident,"[Cc]rash") == TRUE) |>
  mutate(factor = "Crash") |>
  relocate(factor, .after = race)

rain_df = reason_fatal_df1 |>
 filter(str_detect(incident,"[Rr]ain") == TRUE) |>
   mutate(factor = "Rain") |>
  relocate(factor, .after = race)


# Split reasons for multiple reasons mentioned from one cell
other_df = reason_fatal_df1 |>
  filter(!str_detect(incident,"[Rr]ain|[Cc]rash")) |>
  mutate(factor = NA) |>
  relocate(factor, .after = race) |>
  mutate(excluded = ifelse(excluded == "Philippe Streiff", NA, excluded)) # “Philippe Streiff” is not related to this cell

other_1987_df = tibble(race = "1987 Austrian Grand Prix",
                        lap = 1,
                        resumed = "Resumed",
                        incident = c("Nigel Mansell crawled away with clutch problems.", 
                                     "Eddie Cheever and Riccardo Patrese collided.",
                                     "Stefan Johansson, Alex Caffi, Ivan Capelli, Pascal Fabre, Philippe Alliot, Martin Brundle and Christian Danner were involved in the ensuing pile-up."),
                        excluded = NA,
                        factor = c("Vehicle Function",
                                   "Collision",
                                   "Collision"))

other_

```

